TRAINING:
  seed: 42
  train_ratio: 0.7
  epochs: 20
  learning_rate: 0.0005
  scheduler_step: 10
  scheduler_gamma: 0.1
  check_point_uri: 'ckpts/mode_net_40/dgcnn'
  pretrained_uri: 'ckpts/mode_net_40/model_net_40'

FEWSHOT:
  n_ways: 10
  k_shots: 10
  n_tasks: 10
  test_k_shots: [5, 10, 15, 20]

DATASET:
  name: 'ModelNet40'
  # dataset_source : 'data/shape_net_55/preprocessed_shapenet/shape_net_pcd.npy'
  # label_source: 'data/shape_net_55/preprocessed_shapenet/shape_net_labels.npy'
  dataset_source : 'data/model_net_40c/data_original.npy'
  label_source: 'data/model_net_40c/model_net_labels.npy'
  num_classes: 40
  data_loader_num_workers: 5
  batch_size: 8
  experiment_result_uri: 'experiment_results'


TESTING:
  model_state: 'ckpts/mode_net_40/proto_net_40/proto_net_7'
  dataset_path: 'data/test_set/proto_net_test.pickle'
