TRAINING:
  seed: 42
  train_ratio: 0.8
  epochs: 130
  learning_rate: 0.0005
  scheduler_step: 10
  scheduler_gamma: 0.1
  check_point_uri: 'ckpts/proto_net_40/proto_net_2'

FEWSHOT:
  n_ways: 5
  k_shots: 10
  n_tasks: 10
  test_k_shots: [5, 10, 15, 20]

DATASET:
  name: 'ModelNet40'
  dataset_source : 'data/model_net_40c/data_original.npy'
  label_source: 'data/model_net_40c/label.npy'
  num_classes: 40
  data_loader_num_workers: 5
  batch_size: 34


TESTING:
  model_state: 'ckpts/proto_net_40/proto_net_2'
